import { PrismaClient, EventType, SignUpMethod } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // ── Venues ──────────────────────────────────────────────────────────────────
  const venues = await Promise.all([
    prisma.venue.upsert({
      where: { id: 'venue-1' },
      update: {},
      create: {
        id: 'venue-1',
        name: 'The Bitter End',
        address: '147 Bleecker St',
        neighborhood: 'Greenwich Village',
        city: 'New York',
        state: 'NY',
        lat: 40.7282,
        lng: -74.0,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-2' },
      update: {},
      create: {
        id: 'venue-2',
        name: 'Rockwood Music Hall',
        address: '196 Allen St',
        neighborhood: 'Lower East Side',
        city: 'New York',
        state: 'NY',
        lat: 40.7218,
        lng: -73.9876,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-3' },
      update: {},
      create: {
        id: 'venue-3',
        name: 'Bar Chord',
        address: '1008 Cortelyou Rd',
        neighborhood: 'Ditmas Park',
        city: 'Brooklyn',
        state: 'NY',
        lat: 40.6418,
        lng: -73.9638,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-4' },
      update: {},
      create: {
        id: 'venue-4',
        name: 'The Sidewalk Cafe',
        address: '94 Ave A',
        neighborhood: 'East Village',
        city: 'New York',
        state: 'NY',
        lat: 40.7265,
        lng: -73.9816,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-5' },
      update: {},
      create: {
        id: 'venue-5',
        name: 'Branded Saloon',
        address: '603 Vanderbilt Ave',
        neighborhood: 'Prospect Heights',
        city: 'Brooklyn',
        state: 'NY',
        lat: 40.6763,
        lng: -73.9683,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-6' },
      update: {},
      create: {
        id: 'venue-6',
        name: 'The Continental Club',
        address: '1315 S Congress Ave',
        neighborhood: 'South Congress',
        city: 'Austin',
        state: 'TX',
        lat: 30.2499,
        lng: -97.7499,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-7' },
      update: {},
      create: {
        id: 'venue-7',
        name: 'Hole in the Wall',
        address: '2538 Guadalupe St',
        neighborhood: 'The Drag',
        city: 'Austin',
        state: 'TX',
        lat: 30.2895,
        lng: -97.7424,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-8' },
      update: {},
      create: {
        id: 'venue-8',
        name: 'Saxon Pub',
        address: '1320 S Lamar Blvd',
        neighborhood: 'South Lamar',
        city: 'Austin',
        state: 'TX',
        lat: 30.2560,
        lng: -97.7714,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-9' },
      update: {},
      create: {
        id: 'venue-9',
        name: 'Hotel Vegas',
        address: '1502 E 6th St',
        neighborhood: 'East 6th',
        city: 'Austin',
        state: 'TX',
        lat: 30.2607,
        lng: -97.7253,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-10' },
      update: {},
      create: {
        id: 'venue-10',
        name: "Antone's Nightclub",
        address: '305 W 5th St',
        neighborhood: 'Downtown',
        city: 'Austin',
        state: 'TX',
        lat: 30.2674,
        lng: -97.7491,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-11' },
      update: {},
      create: {
        id: 'venue-11',
        name: 'Café Wha?',
        address: '115 Macdougal St',
        neighborhood: 'Greenwich Village',
        city: 'New York',
        state: 'NY',
        lat: 40.7297,
        lng: -74.0006,
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-12' },
      update: {},
      create: {
        id: 'venue-12',
        name: 'Pianos',
        address: '158 Ludlow St',
        neighborhood: 'Lower East Side',
        city: 'New York',
        state: 'NY',
        lat: 40.7220,
        lng: -73.9884,
      },
    }),
  ]);

  console.log(`Seeded ${venues.length} venues`);

  // ── Events ───────────────────────────────────────────────────────────────────
  const now = new Date();
  const d = (daysFromNow: number, hour: number) => {
    const dt = new Date(now);
    dt.setDate(dt.getDate() + daysFromNow);
    dt.setHours(hour, 0, 0, 0);
    return dt;
  };

  const events = await Promise.all([
    prisma.event.upsert({
      where: { id: 'event-1' },
      update: {},
      create: {
        id: 'event-1',
        venueId: 'venue-1',
        title: 'Monday Open Mic Night',
        description: 'All genres welcome. Sign up at the door from 7 PM. Hosted by DJ Rosa.',
        startsAt: d(0, 19),
        endsAt: d(0, 23),
        type: EventType.OPEN_MIC,
        genres: ['Folk', 'Singer-Songwriter', 'Indie'],
        coverCharge: 'Free',
        slotDuration: '5 min',
        backline: ['PA', 'Acoustic Guitar', 'Keyboard'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Monday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-2' },
      update: {},
      create: {
        id: 'event-2',
        venueId: 'venue-2',
        title: 'Tuesday Jazz Jam',
        description: 'Open jam for all jazz musicians. House rhythm section provided.',
        startsAt: d(1, 21),
        endsAt: d(2, 1),
        type: EventType.JAM_SESSION,
        genres: ['Jazz', 'Bebop', 'Fusion'],
        coverCharge: '$5',
        slotDuration: 'Open',
        backline: ['Drums', 'Bass Amp', 'PA', 'Piano'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Tuesday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-3' },
      update: {},
      create: {
        id: 'event-3',
        venueId: 'venue-3',
        title: 'Brooklyn Open Mic',
        description: 'Music, comedy, spoken word — all welcome. No experience required.',
        startsAt: d(2, 20),
        endsAt: d(2, 23),
        type: EventType.OPEN_MIC,
        genres: ['Any'],
        coverCharge: 'Free',
        slotDuration: '7 min',
        backline: ['PA', 'Mic Stand'],
        signUpMethod: SignUpMethod.APP,
        isRecurring: true,
        recurringDescription: 'Every Wednesday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-4' },
      update: {},
      create: {
        id: 'event-4',
        venueId: 'venue-4',
        title: 'Anti-Folk Open Stage',
        description: 'The original anti-folk stage. Raw, weird, and wonderful.',
        startsAt: d(3, 19),
        endsAt: d(3, 22),
        type: EventType.OPEN_STAGE,
        genres: ['Anti-Folk', 'Experimental', 'Punk'],
        coverCharge: 'Free',
        slotDuration: '3 songs',
        backline: ['PA', 'Guitar Amp', 'Drum Kit'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: false,
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-5' },
      update: {},
      create: {
        id: 'event-5',
        venueId: 'venue-5',
        title: 'Comedy Open Mic',
        description: '5 minutes each. Bring your best material or your worst — we take both.',
        startsAt: d(4, 20),
        endsAt: d(4, 23),
        type: EventType.COMEDY_NIGHT,
        genres: [],
        coverCharge: 'Free',
        slotDuration: '5 min',
        backline: ['PA', 'Mic Stand'],
        signUpMethod: SignUpMethod.ONLINE,
        isRecurring: true,
        recurringDescription: 'Every Friday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-6' },
      update: {},
      create: {
        id: 'event-6',
        venueId: 'venue-1',
        title: 'Saturday Blues Jam',
        description: 'All instruments welcome. House band kicks things off at 9.',
        startsAt: d(5, 21),
        endsAt: d(6, 1),
        type: EventType.JAM_SESSION,
        genres: ['Blues', 'R&B', 'Soul'],
        coverCharge: '$10 at door',
        slotDuration: 'Open',
        backline: ['Full Backline', 'PA'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Saturday',
        isApproved: true,
      },
    }),

    // ── Austin events ─────────────────────────────────────────────────────────

    prisma.event.upsert({
      where: { id: 'event-7' },
      update: {},
      create: {
        id: 'event-7',
        venueId: 'venue-6',
        title: 'Sunday Night Open Mic',
        description: 'Austin\'s longest-running open mic. All originals, no covers. Sign up at 7 PM.',
        startsAt: d(6, 19),
        endsAt: d(6, 23),
        type: EventType.OPEN_MIC,
        genres: ['Country', 'Blues', 'Americana'],
        coverCharge: 'Free',
        slotDuration: '10 min',
        backline: ['PA', 'Guitar Amp', 'Drum Kit'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Sunday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-8' },
      update: {},
      create: {
        id: 'event-8',
        venueId: 'venue-7',
        title: 'Drag Open Mic',
        description: 'Student-friendly open mic near UT. Original music encouraged. Free parking in the back.',
        startsAt: d(1, 20),
        endsAt: d(1, 23),
        type: EventType.OPEN_MIC,
        genres: ['Indie', 'Alternative', 'Folk'],
        coverCharge: 'Free',
        slotDuration: '8 min',
        backline: ['PA', 'Mic Stand', 'DI Box'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Tuesday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-9' },
      update: {},
      create: {
        id: 'event-9',
        venueId: 'venue-8',
        title: 'Wednesday Night Jam',
        description: 'House band leads the jam from 9 PM. Guitarists, horns, keys — bring it all.',
        startsAt: d(2, 21),
        endsAt: d(3, 1),
        type: EventType.JAM_SESSION,
        genres: ['Rock', 'Blues', 'Funk'],
        coverCharge: 'Free',
        slotDuration: 'Open',
        backline: ['Full Backline', 'Horns PA', 'Keys'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Wednesday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-10' },
      update: {},
      create: {
        id: 'event-10',
        venueId: 'venue-9',
        title: 'East Side Comedy Open Mic',
        description: 'Sign up list opens at 8. 5 minutes each, no exceptions. Industry folks in the house.',
        startsAt: d(3, 20),
        endsAt: d(3, 23),
        type: EventType.COMEDY_NIGHT,
        genres: [],
        coverCharge: 'Free',
        slotDuration: '5 min',
        backline: ['PA', 'Mic Stand'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Thursday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-11' },
      update: {},
      create: {
        id: 'event-11',
        venueId: 'venue-10',
        title: 'Antone\'s Open Blues Jam',
        description: 'Legendary Austin blues club opens the stage every Friday. All levels welcome.',
        startsAt: d(4, 22),
        endsAt: d(5, 2),
        type: EventType.JAM_SESSION,
        genres: ['Blues', 'Texas Blues', 'R&B'],
        coverCharge: '$5',
        slotDuration: 'Open',
        backline: ['Full Backline', 'PA', 'Vintage Amps'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Friday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-12' },
      update: {},
      create: {
        id: 'event-12',
        venueId: 'venue-6',
        title: 'Songwriters in the Round',
        description: 'Three songwriters share original songs and stories in an intimate round format.',
        startsAt: d(5, 19),
        endsAt: d(5, 22),
        type: EventType.OPEN_STAGE,
        genres: ['Country', 'Singer-Songwriter', 'Americana'],
        coverCharge: 'Free',
        slotDuration: '15 min',
        backline: ['PA', 'Acoustic Guitar', 'Stool'],
        signUpMethod: SignUpMethod.ONLINE,
        isRecurring: false,
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-13' },
      update: {},
      create: {
        id: 'event-13',
        venueId: 'venue-9',
        title: 'Punk & Hardcore Open Mic',
        description: 'Loud, fast, and free. PA, guitar amp, and a drum kit. Bring your crew.',
        startsAt: d(0, 21),
        endsAt: d(1, 0),
        type: EventType.OPEN_MIC,
        genres: ['Punk', 'Hardcore', 'Post-Punk'],
        coverCharge: 'Free',
        slotDuration: '3 songs',
        backline: ['Guitar Amp', 'Bass Amp', 'Drum Kit', 'PA'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: false,
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-14' },
      update: {},
      create: {
        id: 'event-14',
        venueId: 'venue-8',
        title: 'Open Poetry Slam',
        description: 'Three minutes, no props, no costumes. Just words. Judged by the audience.',
        startsAt: d(1, 19),
        endsAt: d(1, 22),
        type: EventType.POETRY_SLAM,
        genres: [],
        coverCharge: 'Free',
        slotDuration: '3 min',
        backline: ['PA', 'Mic Stand'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Tuesday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-15' },
      update: {},
      create: {
        id: 'event-15',
        venueId: 'venue-7',
        title: 'Guitar Workshop: Fingerpicking Fundamentals',
        description: 'Hands-on workshop with local guitarist Marcus Webb. Bring your acoustic. Beginners welcome.',
        startsAt: d(3, 14),
        endsAt: d(3, 17),
        type: EventType.WORKSHOP,
        genres: ['Acoustic', 'Fingerpicking', 'Folk'],
        coverCharge: '$10 at door',
        slotDuration: undefined,
        backline: ['PA', 'Acoustic Guitar'],
        signUpMethod: SignUpMethod.ONLINE,
        isRecurring: false,
        isApproved: true,
      },
    }),

    // ── More New York events ───────────────────────────────────────────────────

    prisma.event.upsert({
      where: { id: 'event-16' },
      update: {},
      create: {
        id: 'event-16',
        venueId: 'venue-11',
        title: 'Greenwich Village Open Mic',
        description: 'Walk-in open mic on the historic stage where Jimi Hendrix and Dylan got their start.',
        startsAt: d(2, 19),
        endsAt: d(2, 22),
        type: EventType.OPEN_MIC,
        genres: ['Rock', 'Folk', 'Singer-Songwriter'],
        coverCharge: 'Free',
        slotDuration: '7 min',
        backline: ['PA', 'Guitar Amp', 'Keyboard'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Wednesday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-17' },
      update: {},
      create: {
        id: 'event-17',
        venueId: 'venue-12',
        title: 'LES Comedy Open Mic',
        description: 'Late-night comedy in the heart of the Lower East Side. Sign up starts at 9.',
        startsAt: d(4, 21),
        endsAt: d(5, 0),
        type: EventType.COMEDY_NIGHT,
        genres: [],
        coverCharge: 'Free',
        slotDuration: '5 min',
        backline: ['PA', 'Mic Stand'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Friday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-18' },
      update: {},
      create: {
        id: 'event-18',
        venueId: 'venue-2',
        title: 'Sunday Singer-Songwriter Circle',
        description: 'Intimate afternoon of original music. 10-minute slots, mellow vibe.',
        startsAt: d(6, 15),
        endsAt: d(6, 18),
        type: EventType.OPEN_STAGE,
        genres: ['Singer-Songwriter', 'Indie Folk', 'Acoustic'],
        coverCharge: 'Free',
        slotDuration: '10 min',
        backline: ['PA', 'Acoustic Guitar', 'DI Box'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Sunday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-19' },
      update: {},
      create: {
        id: 'event-19',
        venueId: 'venue-3',
        title: 'Brooklyn Poetry Slam',
        description: 'Open to all — beginner to seasoned. Sign-up sheet at the bar. $50 prize for the winner.',
        startsAt: d(0, 19),
        endsAt: d(0, 22),
        type: EventType.POETRY_SLAM,
        genres: [],
        coverCharge: 'Free',
        slotDuration: '3 min',
        backline: ['PA', 'Mic Stand'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: false,
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-20' },
      update: {},
      create: {
        id: 'event-20',
        venueId: 'venue-4',
        title: 'Thursday Jazz Jam',
        description: 'House rhythm section sets the groove. Sit in for a song or three.',
        startsAt: d(3, 22),
        endsAt: d(4, 2),
        type: EventType.JAM_SESSION,
        genres: ['Jazz', 'Latin Jazz', 'Fusion'],
        coverCharge: 'Free',
        slotDuration: 'Open',
        backline: ['Drums', 'Bass Amp', 'Piano', 'PA'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Thursday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-21' },
      update: {},
      create: {
        id: 'event-21',
        venueId: 'venue-5',
        title: 'Prospect Heights Open Mic',
        description: 'Neighborhood open mic in a cozy bar setting. Any genre, any level.',
        startsAt: d(5, 20),
        endsAt: d(5, 23),
        type: EventType.OPEN_MIC,
        genres: ['Any'],
        coverCharge: 'Free',
        slotDuration: '5 min',
        backline: ['PA', 'Mic Stand'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Saturday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-22' },
      update: {},
      create: {
        id: 'event-22',
        venueId: 'venue-10',
        title: 'Vocal Workshop: Stage Presence & Mic Technique',
        description: 'Two-hour workshop led by touring vocalist Delia Cruz. Limited to 12 participants.',
        startsAt: d(4, 13),
        endsAt: d(4, 15),
        type: EventType.WORKSHOP,
        genres: ['Vocals', 'Performance'],
        coverCharge: '$15',
        slotDuration: undefined,
        backline: ['PA', 'Wireless Mics'],
        signUpMethod: SignUpMethod.ONLINE,
        isRecurring: false,
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-23' },
      update: {},
      create: {
        id: 'event-23',
        venueId: 'venue-11',
        title: 'Open Studio Night',
        description: 'Bring your canvas, your laptop, your sketchbook. Chill music, no pressure.',
        startsAt: d(1, 18),
        endsAt: d(1, 22),
        type: EventType.OPEN_STUDIO,
        genres: [],
        coverCharge: 'Free',
        slotDuration: undefined,
        backline: [],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Tuesday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-24' },
      update: {},
      create: {
        id: 'event-24',
        venueId: 'venue-8',
        title: 'Friday Night Open Mic',
        description: 'S. Lamar\'s go-to open mic. 8-minute sets, original music preferred.',
        startsAt: d(4, 21),
        endsAt: d(5, 1),
        type: EventType.OPEN_MIC,
        genres: ['Country', 'Rock', 'Indie'],
        coverCharge: 'Free',
        slotDuration: '8 min',
        backline: ['PA', 'Guitar Amp', 'Drum Kit'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Friday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-25' },
      update: {},
      create: {
        id: 'event-25',
        venueId: 'venue-12',
        title: 'Sunday Experimental Jam',
        description: 'No genre limits. Electronics, noise, jazz, ambient — bring whatever you make sound with.',
        startsAt: d(6, 17),
        endsAt: d(6, 21),
        type: EventType.JAM_SESSION,
        genres: ['Experimental', 'Ambient', 'Noise', 'Improv'],
        coverCharge: 'Free',
        slotDuration: 'Open',
        backline: ['PA', 'Mixer', 'Guitar Amp'],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: true,
        recurringDescription: 'Every Sunday',
        isApproved: true,
      },
    }),
    prisma.event.upsert({
      where: { id: 'event-26' },
      update: {},
      create: {
        id: 'event-26',
        venueId: 'venue-9',
        title: 'Open Studio: Illustration & Zine Making',
        description: 'Drop in to draw, cut, paste, and print. Supplies provided. All skill levels.',
        startsAt: d(2, 16),
        endsAt: d(2, 20),
        type: EventType.OPEN_STUDIO,
        genres: [],
        coverCharge: 'Free',
        slotDuration: undefined,
        backline: [],
        signUpMethod: SignUpMethod.DOOR,
        isRecurring: false,
        isApproved: true,
      },
    }),
  ]);

  console.log(`Seeded ${events.length} events`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
